In [12]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
from proj1_helpers import *
from data_helpers import *

from cross_validation import *

from plots import *


In [14]:
DATA_TRAIN_PATH = 'data/train.csv'
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [15]:
tx_clean = remove_undefined_values (tX)


[ 1.21858528e+02  4.92398193e+01  8.11819816e+01  5.78959617e+01
  2.40373503e+00  3.71783360e+02 -8.21688171e-01  2.37309984e+00
  1.89173324e+01  1.58432217e+02  1.43760943e+00 -1.28304708e-01
  4.58289801e-01  3.87074191e+01 -1.09730480e-02 -8.17107200e-03
  4.66602072e+01 -1.95074680e-02  4.35429640e-02  4.17172345e+01
 -1.01191920e-02  2.09797178e+02  9.79176000e-01  8.48221045e+01
 -3.27458741e-03 -1.23928255e-02  5.76794744e+01 -1.18452642e-02
 -1.58228913e-03  7.30645914e+01]
(30,)


In [16]:
#MODEL BUILDING

tx, mean, std = standardize(tx_clean,0)
y, tx = build_model_data(tx,y)
tx

array([[ 1.00000000e+00,  3.14910656e-01,  6.83319669e-02, ...,
         1.14381874e+00, -2.52714288e+00,  4.12510497e-01],
       [ 1.00000000e+00,  7.40827026e-01,  5.52504823e-01, ...,
         2.27720906e-14, -9.07315481e-15, -2.73819964e-01],
       [ 1.00000000e+00, -1.00190288e-12,  3.19515553e+00, ...,
         2.27720906e-14, -9.07315481e-15, -2.93969845e-01],
       ...,
       [ 1.00000000e+00, -3.10930673e-01,  3.19316447e-01, ...,
         2.27720906e-14, -9.07315481e-15, -3.17017229e-01],
       [ 1.00000000e+00, -5.10097335e-01, -8.45323970e-01, ...,
         2.27720906e-14, -9.07315481e-15, -7.45439413e-01],
       [ 1.00000000e+00, -1.00190288e-12,  6.65336083e-01, ...,
         2.27720906e-14, -9.07315481e-15, -7.45439413e-01]])

In [17]:
np.mean(tx,axis=0)

array([ 1.00000000e+00, -9.73058263e-13,  4.50019089e-15, -3.48448848e-15,
        7.19675786e-15, -7.23439743e-12, -6.30188859e-12,  6.80668756e-13,
        2.16429719e-14,  6.39742126e-15,  2.86409207e-15, -7.00447966e-15,
        4.45924897e-15,  5.55781326e-13, -5.96492045e-15,  1.35646161e-16,
        7.13136217e-17,  2.58030370e-14, -1.06327391e-16, -1.87188487e-16,
        8.24369382e-15,  1.41040513e-16, -9.00283004e-15, -6.01698247e-16,
        2.89129663e-12, -2.76637638e-15,  2.53942997e-14, -8.40723516e-12,
        2.10209062e-14, -5.90180110e-15, -8.76751116e-16])

In [18]:
for i in range(len(y)):
    if y[i] == -1:
        y[i] = 0
y

array([1., 0., 0., ..., 1., 0., 0.])

In [19]:
num_samples = len(y)
num_features = tx.shape[1]

num_samples, num_features
tx.shape

(250000, 31)

In [20]:
from compute_gradient import *
from cost import *
from implementations import *
w = np.zeros((num_features,1))
max_iter = 100
threshold = 1e-8

gamma = 0.001
losses = []
w.shape,tx.shape
y = y.reshape(num_samples,1)
gradient = 0
w.shape

(31, 1)

In [21]:
    for iter in range(max_iter):
        for batch_y, batch_tx in batch_iter(y, tx, batch_size=1, num_batches = num_samples):
            
            gradient = logistic_gradient (batch_y,batch_tx,w)
            w -= gamma*gradient
            #print("Gradient={g}".format(g=gradient))
            #print(w)
            loss = logistic_loss (batch_y,batch_tx,w)
            # log info
            #if iter % 100 == 0:
            #print("Current iteration={i}, loss={l}".format(i=iter, l=loss))
            
            losses.append(loss)
        print("Gradient Descent({bi}/{ti}): loss={l}".format(
                  bi=iter, ti=max_iter - 1, l=loss))
            #if len(losses) > 1 and np.abs(losses[-1] - losses[-2]) < threshold:
            #break

        print("loss={l}".format(l=logistic_loss(y, tx, w)))

Gradient Descent(0/99): loss=1.5164181848147633
loss=125102.92019608324
Gradient Descent(1/99): loss=0.447014484520141
loss=125158.64969908416
Gradient Descent(2/99): loss=0.08908384627271973
loss=125178.59546827854
Gradient Descent(3/99): loss=0.06436608509869615
loss=125286.84023782398
Gradient Descent(4/99): loss=0.13409170465664452
loss=125213.14045440257
Gradient Descent(5/99): loss=0.13034417106402357
loss=125243.31249051802
Gradient Descent(6/99): loss=0.28414573113524527
loss=125107.578425168
Gradient Descent(7/99): loss=1.4492882919691072
loss=125044.79285659581
Gradient Descent(8/99): loss=0.8393079326212982
loss=125050.1389223676
Gradient Descent(9/99): loss=0.05430489293743843
loss=125109.1972910757
Gradient Descent(10/99): loss=0.03419215114925409
loss=125108.54898459098
Gradient Descent(11/99): loss=0.5716694037657313
loss=125260.27247877914
Gradient Descent(12/99): loss=0.5103258634603682
loss=125116.12283455356
Gradient Descent(13/99): loss=0.048056810526393004
loss=125

In [29]:
w
loss/num_samples

3.058844101854333e-06

In [30]:
DATA_TEST_PATH = 'data/test.csv'
ytest, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [33]:
ytest.shape

(568238,)

In [31]:
tx_test_clean = remove_undefined_values (tX_test)
tx_test, _, _ = standardize(tx_test_clean,0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [26]:
ytest, tx_test = build_model_data(tx_test,ytest)

In [27]:
OUTPUT_PATH = 'data/submission_ridge.csv'
y_pred = predict_labels(w, tx_test,'logistic')
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)