In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [2]:
from proj1_helpers import *
from data_helpers import *
from cross_validation import *
from plots import *

In [3]:
#LOAD TRAINING DATA
DATA_TRAIN_PATH = 'data/train.csv'
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [4]:
#CLEAN TRAINING DATA
bounds = [0.0, 0.5]
tx_clean, ind_remov = treat_undefined_values(bounds, tX)
ind_remov

[4, 5, 6, 12, 26, 27, 28]

In [5]:
#MODEL BUILDING
tx, mean, std = standardize(tx_clean,0)
tx_augmented = build_poly_all_features(tx,3)
y,tx = build_model_data(tx_augmented,y)
y = classify(y)
num_samples = len(y)
num_features = tx.shape[1]
y = y.reshape(num_samples,1)


In [6]:
num_samples, num_features
tx.shape

(250000, 70)

In [7]:
from compute_gradient import *
from cost import *
from implementations import *

In [8]:
#Initial weight


#Maximum iterations through the whole set
max_iter = 100

#0.001 nan
#0.0005 nan

#Step-size
gammas = np.logspace(-6,-1, 7)
lambdas = np.logspace (-6,-1,7)


#Regularization factor
# lambda_ = 0.01 142000 loss 10 000 iters
#lambda_ = 0.001 141000 loss 10 000 iters
#lambda_ = 0.02
#loss_min = np.inf
tx.shape,y.shape,y

((250000, 70), (250000, 1), array([[1.],
        [0.],
        [0.],
        ...,
        [1.],
        [0.],
        [0.]]))

In [19]:
losses_tr = np.zeros((len(gammas),len(lambdas)))
losses_val = np.zeros((len(gammas),len(lambdas)))

k_fold = 2
seed = 1
loss_min = np.inf
initial_w = np.zeros((tx.shape[1],1))
max_accuracy = 0
#CHOOSE LAMBDA AND GAMMA
for ind_lambda, lambda_ in enumerate(lambdas):
    for ind_gamma ,gamma_ in enumerate (gammas):
        loss_training = 0
        loss_validation = 0
        training_accuracy = 0
        validation_accuracy = 0
        for i,k in enumerate(range(k_fold)):
            
            tx_train, y_train, tx_val, y_val = cross_validation(y, tx, k, k_fold, seed)
            w, loss_train_k = reg_logistic_regression(y_train, tx_train, lambda_, initial_w, max_iter, gamma_)
            loss_val_k = reg_logistic_loss (y_val,tx_val,w,lambda_)/len(y_val)
            #loss_train_k /= len(y_train)
            loss_training += loss_train_k
            loss_validation += loss_val_k
            training_accuracy += predict_accuracy(y_train,tx_train,w)
            validation_accuracy += predict_accuracy(y_val,tx_val,w)
        
        training_accuracy /= k_fold
        validation_accuracy /= k_fold
        loss_training /= k_fold
        loss_validation /= k_fold
        print(lambda_)
        print(gamma_)
        print(loss_training)
        print(loss_validation)
        print(training_accuracy)
        print(validation_accuracy)
        if (validation_accuracy > max_accuracy):
            weights_star = w
            lambda_star = lambda_
            gamma_star = gamma_
            loss_min = loss_validation
            max_accuracy = validation_accuracy
            
        losses_tr[ind_lambda][ind_gamma] = loss_training
        losses_val[ind_lambda][ind_gamma] = loss_validation



1e-06
1e-06
0.6931928748784768
0.6928812429186292
65.7324
65.72919999999999
1e-06
6.8129206905796085e-06
0.6936167267334739
0.6921006315921631
65.75280000000001
65.7748


/Users/Sofia/Desktop/ML_Project1/cost.py:20: RuntimeWarning: divide by zero encountered in log
  loss = y.T.dot(np.log(pred)) + (1 - y).T.dot(np.log(1 - pred))


1e-06
4.641588833612782e-05
0.6945158883079265
nan
65.9084
65.9324
1e-06
0.00031622776601683794
0.6825933753593655
nan
66.1192
66.13
1e-06
0.0021544346900318843
0.6556431884258214
nan
65.69839999999999
65.7124
1e-06
0.014677992676220705
0.4758616046670533
nan
68.418
68.3852
1e-06
0.1
0.007607297084776135
nan
64.0472
64.1232
6.8129206905796085e-06
1e-06
0.0713417800811576
nan
62.449600000000004
62.449600000000004
6.8129206905796085e-06
6.8129206905796085e-06
0.07129049039965242
nan
62.4544
62.4544
6.8129206905796085e-06
4.641588833612782e-05
0.07094250506559188
nan
62.476
62.474000000000004
6.8129206905796085e-06
0.00031622776601683794
0.0686368795696109
nan
62.6036
62.614000000000004
6.8129206905796085e-06
0.0021544346900318843
0.05549291772255874
nan
63.385999999999996
63.3644
6.8129206905796085e-06
0.014677992676220705
0.025908375298101784
nan
65.5832
65.5284
6.8129206905796085e-06
0.1
0.062226961973989484
nan
67.4488
67.3416
4.641588833612782e-05
1e-06
3.5229450940404714
nan
66.0091

In [26]:
lambdas

array([1.00000000e-05, 4.64158883e-05, 2.15443469e-04, 1.00000000e-03,
       4.64158883e-03, 2.15443469e-02, 1.00000000e-01])

In [27]:
gammas

array([1.00000000e-06, 6.81292069e-06, 4.64158883e-05, 3.16227766e-04,
       2.15443469e-03, 1.46779927e-02, 1.00000000e-01])

In [28]:
losses_tr, losses_val

(array([[0.69319692,        inf,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan]]),
 array([[0.69288124, 0.69210063,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
  

In [22]:
loss_min, lambda_star, gamma_star

(nan, 0.0021544346900318843, 0.014677992676220705)

In [23]:
#PREDICT TRAINING ACCURACY
training_accuracy = predict_accuracy(y,tx,weights_star)
training_accuracy

57.5268

In [25]:
#LOAD TEST SET
DATA_TEST_PATH = 'data/test.csv'
ytest, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [26]:
#CLEAN AND STANDARDIZE TEST SET
tX_test_clean = np.delete(tX_test, ind_remov, axis=1)
tX_test_clean.shape


(568238, 23)

In [27]:
bound = [0.0, 1.0]
tx_test_clean,_ = treat_undefined_values (bound,tX_test_clean)
tx_test_clean.shape

(568238, 23)

In [28]:
tx_test_clean, _, _ = standardize(tx_test_clean,0)


In [29]:
tx_test_augmented = build_poly_all_features(tx_test_clean,3)

In [30]:
tx_test_augmented.shape

(568238, 69)

In [31]:
#BUILD TEST MODEL
ytest, tx_test = build_model_data(tx_test_augmented,ytest)
tx_test.shape

(568238, 70)

In [32]:
#PREDICT LABELS
OUTPUT_PATH = 'data/submission_reg_logistic-degre3.csv'
y_pred = predict_labels(weights_star, tx_test,'logistic')
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)