In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [2]:
from proj1_helpers import *
from data_helpers import *
from cross_validation import *
from plots import *
from compute_gradient import *
from cost import *
from implementations import *

In [22]:
#LOAD TRAINING DATA
DATA_TRAIN_PATH = 'data/train.csv'
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
print(y)

[ 1. -1. -1. ...  1. -1. -1.]


In [10]:
#CLEAN TRAINING DATA
bounds = [0.0, 0.5]
tx_clean, ind_remov = treat_undefined_values(bounds, tX)
print(ind_remov)
print(tx_clean.shape)

[4, 5, 6, 12, 26, 27, 28]
(250000, 23)


In [24]:
#MODEL BUILDING
tx, mean, std = standardize(tx_clean,0)
tx_augmented = build_poly_all_features(tx,3) #to be determined
y,tx = build_model_data(tx_augmented,y)
y = classify(y)
num_samples = len(y)
num_features = tx.shape[1]
y = y.reshape(num_samples,1)
print(y)

[[1.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]
[[1.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]
[[1.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]


In [12]:
print(num_samples, num_features)
print(tx.shape)

250000 70
(250000, 70)


In [27]:
#Initial weight
initial_w = np.zeros((num_features,1))

#Maximum iterations through the whole set
max_iter = 20

#0.001 nan
#0.0005 nan

#Step-size
gamma = 0.014 #to be determined

#Regularization factor
lambda_ = 0.002 #to be determined

print(tx.shape)
print(y.shape)
print(y)

(250000, 70)
(250000, 1)
[[1.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]


In [28]:
w, loss = reg_logistic_regression(y, tx, lambda_, initial_w, max_iter, gamma)

[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]


In [29]:
print(y.shape)

(250000, 1)


In [30]:
#PREDICT TRAINING ACCURACY
training_accuracy = predict_accuracy(y,tx,w)
training_accuracy

71.17

In [31]:
#LOAD TEST SET
DATA_TEST_PATH = 'data/test.csv'
ytest, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [32]:
#CLEAN AND STANDARDIZE TEST SET
tX_test_clean = np.delete(tX_test, ind_remov, axis=1)
tX_test_clean.shape


(568238, 23)

In [33]:
bound = [0.0, 1.0]
tx_test_clean = remove_undefined_values (tX_test_clean)
tx_test_clean.shape

(568238, 23)

In [34]:
tx_test_clean, _, _ = standardize(tx_test_clean,0)

In [35]:
tx_test_augmented = build_poly_all_features(tx_test_clean,3)

In [36]:
tx_test_augmented.shape

(568238, 69)

In [37]:
#BUILD TEST MODEL
ytest, tx_test = build_model_data(tx_test_augmented,ytest)

In [38]:
#PREDICT LABELS
OUTPUT_PATH = 'data/submission_reg_logistic-degre2.csv'
y_pred = predict_labels(w, tx_test,'logistic')
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)